name: Build and Release Docker Image

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build Docker image
      run: |
        docker build --no-cache --label FIKA -t fika .

    - name: Save Docker image as tarball
      run: |
        docker save -o fika-docker-image.tar fika

    - name: Upload Docker image as artifact
      uses: actions/upload-artifact@v2
      with:
        name: fika-docker-image
        path: ./fika-docker-image.tar
