name: Build and Release Docker Image

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build Docker image
      run: |
        docker build --no-cache --label FIKA -t fika .

    - name: Save Docker image as artifact
      uses: actions/upload-artifact@v4
      with:
        name: fika-docker-image
        path: .   # Change this path to the directory where your Dockerfile is located

    - name: Get short SHA
      id: short_sha
      run: echo $GITHUB_SHA | head -c 7

    - name: Create a Release
      uses: elgohr/Github-Release-Action@v5
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        title: ${{ steps.short_sha.outputs.stdout }}
