name: Build and Release Docker Image

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Get current date in YYYY-MM-DD format
      run: echo "VERSION=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

    - name: Build Docker image
      run: |
        docker build --no-cache --label FIKA -t fika .

    - name: Save Docker image as tarball
      run: |
        docker save -o fika-docker-image-${{ env.VERSION }}.tar fika

    - name: Upload Docker image artifact
      uses: actions/upload-artifact@v4
      with:
        name: fika-docker-image-${{ env.VERSION }}
        path: ./fika-docker-image-${{ env.VERSION }}.tar

    - name: Create release with action-gh-release
      uses: softprops/action-gh-release@v2  # Use the latest stable version (check for updates)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needs write access to repo
      with:
        tag_name: ${{ env.VERSION }}
        name: "Release v${{ env.VERSION }}"  # Optional: customize release name
        body: "Built using the latest fika and spt versions on ${{ env.VERSION }}"
        draft: false  # Set to true to create draft releases
        files: ./fika-docker-image-${{ env.VERSION }}.tar  # Upload the artifact as release asset
