name: Build and Release Docker Image

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Get current date in YYYY-MM-DD format
      run: echo "VERSION=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

    - name: Build Docker image
      run: |
        docker build --no-cache --label FIKA -t fika .

    - name: Save Docker image as tarball
      run: |
        docker save -o fika-docker-image-${{ env.VERSION }}.tar fika

    - name: Upload Docker image artifact
      uses: actions/upload-artifact@v4
      with:
        name: fika-docker-image-${{ env.VERSION }}
        path: ./fika-docker-image-${{ env.VERSION }}.tar

    - name: Create release
      uses: actions/create-release@v4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needs write access to repo
      with:
        tag_name: ${{ env.VERSION }}
        release_name: "Release v${{ env.VERSION }}"
        body: "Built and released Docker image on ${{ github.workflow_run_created_at }}"
        draft: false  # Set to true to create draft releases

