name: Build and Release Docker Image

on:
  schedule:
  - cron: "0 0 * * *"
  
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build Docker image
      run: |
        docker build --no-cache --label FIKA -t fika .

    - name: Save Docker image as artifact
      uses: actions/upload-artifact@v2
      with:
        name: fika-docker-image
        path: .   # Change this path to the directory where your Dockerfile is located

    - name: Get short SHA
      run: echo "::set-env name=SHORT_SHA::$(echo $GITHUB_SHA | head -c 7)"

    - name: Create a Release
      uses: elgohr/Github-Release-Action@v5
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        title: ${{ env.SHORT_SHA }}
